Poissonian smearing & linear plots
DmesonAnalysers/DmesonAnalysis pull request #147
Opened 2020-11-03 16:42 UTC by stefanopolitano

2020-11-03 17:02 UTC, fgrosa requested changes
Ciao @stefanopolitano thanks for the PR! I have a couple of comments, when implemented we can merge it

2020-11-03 17:02 UTC, fgrosa commented on optimisation/config_Dplus_pp5TeV_Optimisation.yml
> +    filename: '/home/alidock/DmesonAnalysis/optimisation/BkgCorrFactor/BkgCorrFact_ITS1_AllpT.root' #keep empty if no MC bkg correction is needed
Could you change the default to `''` for this one since no correction factor is needed?

2020-11-03 17:02 UTC, fgrosa commented on optimisation/config_Ds_pp5TeV_Optimisation.yml
> +    filename: '/home/alidock/DmesonAnalysis/optimisation/BkgCorrFactor/BkgCorrFact_ITS1_AllpT.root' #keep empty if no MC bkg correction is needed
Same as Dplus config

2020-11-03 17:02 UTC, fgrosa commented on utils/ReadModel.py
> +def ReadTAMUv2(fileNameTAMUv2):
Is this duplicated for a copy-paste mistake?

2020-11-03 17:20 UTC, stefanopolitano commented
Hi @fgrosa! Thank you for the comments! For what concerns the .yaml files I will change the BkgCorrFactor settings, while, for the  ReadModel.py, I think it is probably a copy-paste mistake, but I will check to be sure.

2020-11-04 13:15 UTC, fgrosa approved these changes

2020-11-04 13:15 UTC, merged