Add pp reference for Ds v2
DmesonAnalysers/DmesonAnalysis pull request #185
Opened 2021-01-15 15:44 UTC by fgrosa

@fcatalan92

2021-01-17 11:34 UTC, fcatalan92 approved these changes

2021-01-17 11:36 UTC, fcatalan92 requested changes
Pls remove the old file (the one of the commint before `fix_name`)

2021-01-17 16:33 UTC, fgrosa commented
> Pls remove the old file (the one of the commint before `fix_name`)

Rremoved, I did not notice that it was not substituted

2021-01-18 08:38 UTC, fcatalan92 approved these changes

2021-01-18 08:38 UTC, merged